import "dotenv/config";
export const env = {
  PORT: process.env.PORT,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  PGSQL_CONNECTIONSTRING: process.env.PGSQL_CONNECTIONSTRING,
  BUILD_MODE: process.env.BUILD_MODE,
};
